name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # ------------
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      # This line enables distribution
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"
      - run: npm ci

      - uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track master origin/master

      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected -t lint test build e2e-ci

        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_PEBBLE_07B8D0100 }}
          node-version: 'v20.12.0'
          cache: 'npm'
          # repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: 'dist/lemon-mart/browser' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

    # ------------
    # - uses: actions/checkout@v4
    #   with:
    #     fetch-depth: 0

    # # Connect your workspace on nx.app and uncomment this to enable task distribution.
    # # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
    # # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"

    # # Cache node_modules
    # - name: use nodejs v4
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 20
    #     cache: 'npm'
    #     # path: node_modules
    #     # key: cache-node-modules-${{hashFiles('package-lock.json')}}
    #     run: npm ci

    # # - name: install deps
    # #   if: steps.cache.outputs.cache-hit != 'true'
    # #   run: npm ci

    # - name: nx shas
    #   uses: nrwl/nx-set-shas@v4
    # - run: |
    #     echo "BASE: ${{env.NX_BASE}}"
    #     echo "HEAD: ${{env.NX_HEAD}}"

    # - run: npm run pretty-format-check
    # - run: npx nx-cloud record -- nx format:check
    # - run: npx nx affected -t lint test build
    # Required for nx affected if we're on a branch
    # - run: git branch --track main origin/master
    # This line enables distribution
    # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
    # - script: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"

    # - name: nx cloud
    # run: npx nx-cloud record -- nx format:check --base=${{github.sha}}~1
    # run: npx nx-cloud record -- nx format:check

    # - name: nx affected
    #   run: npx nx affected -t lint test build e2e-ci
    # run: npx nx affected --base=${{github.sha}}~1 --head=${{github.sha}}~1 -t lint test build
    # run: npx nx affected -t lint test build

  # build_and_deploy_job:
  #   if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
  #   runs-on: ubuntu-latest
  #   name: Azure Deploy Job
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: true
  #         lfs: false
  #     - name: Deploy
  #       id: builddeploy
  #       uses: Azure/static-web-apps-deploy@v1
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_PEBBLE_07B8D0100 }}
  #         node-version: 'v20.12.0'
  #         cache: 'npm'
  #         # repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
  #         action: 'upload'
  #         ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
  #         # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
  #         app_location: '/' # App source code path
  #         api_location: '' # Api source code path - optional
  #         output_location: 'dist/lemon-mart/browser' # Built app content directory - optional
  #         ###### End of Repository/Build Configurations ######
